_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 35
                - 41
                - 55
                - 105
            "2":
                - 1
                - 35
                - 41
                - 55
                - 105
            "3":
                - 2
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
architecture:
    value: Basic ConvNet
batch_size:
    value: 64
dataset:
    value: CIFAR10
dropout_rate:
    value: 0.699218411787199
hidden_size:
    value: 256
lr:
    value: 0.0011750621264166742
num_filters:
    value: 64
